name: UrbIS Sync Pipeline
on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:
jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tippecanoe osmium-tool libosmium2-dev libgdal-dev g++ python3-dev
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install geopandas pyogrio osmium
      - name: Download latest OSM Brussels
        run: |
          wget -O brussels_capital_region-latest.osm.pbf https://download.openstreetmap.fr/extracts/europe/belgium/brussels_capital_region-latest.osm.pbf
      - name: Run Fetch and Generate
        run: |
          python3 fetch-latest.py
      - name: Rename PMTiles
        run: |
          mv addresses.pmtiles addresses.pmtiles.gz
      - name: Check generated files
        run: ls -la *.pmtiles* || echo "Aucun fichier pmtiles trouv√©"
      - name: Commit and Push PMTiles
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add addresses.pmtiles.gz version.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update addresses.pmtiles.gz - $(date +'%Y-%m-%d')"
          git pull --rebase origin main
          git push origin main
